### ISSUE TITLE
Bug : All the proxies are put in Bucket 0.

### ISSUE THREAD

**Issue by tur11ng** [nfx/slrp#130]
The bug is basically stated in the title. I didn't have time to investigate further, but I the Proxy which is always represented as a uint64 is always divisible by 32. Probably using a prime number of shards will fix the error (e.g. 33 instead of 32).

**Comment by nfx** [comment]
Are you sure if it's really the case?

**Comment by st1064870** [comment]
@nfx You can try putting using a debugger and putting a breakpoint on the Add() method and check the data structures. Did you have other findings than me?

**Comment by nfx** [comment]
cannot reproduce.
