### ISSUE TITLE
Curl command in ReadMe no longer works

### ISSUE THREAD

**Issue by Skylion007** [nfx/slrp#153]
The curl command in the readme no longer works and I am not sure how to make it work with a self signed cert. I keep getting the following error when running the command: 

```curl -D - -k -x https://127.0.0.1:8090 -k http://httpbin.org/ip```
```
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
Downgrading from 0.3.0 fixed it.

**Comment by rc5hack** [comment]
Have the same problem with 0.3.0 version.

**Comment by nfx** [comment]
@rc5hack Could you pr the fix for readme?
