### ISSUE TITLE
New sources

### ISSUE THREAD

**Issue by nfx** [nfx/slrp#23]
Sources to be added:

- [ ] #61
- [x] https://www.megaproxylist.net/ (#49)
- [ ] #62

Already done:

- [x] https://api.good-proxies.ru/getfree.php?count=1000&ping=8000&time=600&works=500&key=freeproxy (http) 
- [x] (http) https://api.proxyscrape.com/v2/?request=getproxies&protocol=http
- [x] (http) https://openproxylist.xyz/http.txt
- [x] (http) https://proxyscan.io/download?type=http
- [x] (http) https://proxysearcher.sourceforge.net/Proxy%20List.php?type=http
- [x] (http) https://proxyspace.pro/http.txt
- [x] (http) https://proxyspace.pro/https.txt
- [x] (http) https://raw.githubusercontent.com/almroot/proxylist/master/list.txt
- [x] (http) https://raw.githubusercontent.com/andigwandi/free-proxy/main/proxy_list.txt
- [x] (http) https://raw.githubusercontent.com/aslisk/proxyhttps/main/https.txt
- [x] (http) https://raw.githubusercontent.com/B4RC0DE-TM/proxy-list/main/HTTP.txt
- [x] (http) https://raw.githubusercontent.com/BlackSnowDot/proxylist-update-every-minute/main/http.txt
- [x] (http) https://raw.githubusercontent.com/BlackSnowDot/proxylist-update-every-minute/main/https.txt
- [x] (http) https://raw.githubusercontent.com/fahimscirex/proxybd/master/proxylist/http.txt
- [x] (http) https://raw.githubusercontent.com/hanwayTech/free-proxy-list/main/http.txt
- [x] (http) https://raw.githubusercontent.com/hanwayTech/free-proxy-list/main/https.txt
- [x] (http) https://raw.githubusercontent.com/hendrikbgr/Free-Proxy-Repo/master/proxy_list.txt
- [x] (http) https://raw.githubusercontent.com/HyperBeats/proxy-list/main/http.txt
- [x] (http) https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt
- [x] (http) https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt
- [x] (http) https://raw.githubusercontent.com/mertguvencli/http-proxy-list/main/proxy-list/data.txt
- [x] (http) https://raw.githubusercontent.com/miyukii-chan/proxy-list/master/proxies/http.txt
- [x] (http) https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt
- [x] (http) https://raw.githubusercontent.com/mmpx12/proxy-list/master/https.txt
- [x] (http) https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt
- [x] (http) https://raw.githubusercontent.com/ObcbO/getproxy/master/http.txt
- [x] (http) https://raw.githubusercontent.com/ObcbO/getproxy/master/https.txt
- [x] (http) https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/http/http.txt
- [x] (http) https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/https/https.txt
- [x] (http) https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt
- [x] (http) https://raw.githubusercontent.com/proxylist-to/proxy-list/main/http.txt
- [x] (http) https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies/http.txt
- [x] (http) https://raw.githubusercontent.com/ReCaree/proxy-scrapper/master/proxy/http-removed.txt
- [x] (http) https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt
- [x] (http) https://raw.githubusercontent.com/rx443/proxy-list/main/online/http.txt
- [x] (http) https://raw.githubusercontent.com/rx443/proxy-list/main/online/https.txt
- [x] (http) https://raw.githubusercontent.com/saisuiu/uiu/main/free.txt
- [x] (http) https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/http.txt
- [x] (http) https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt
- [x] (http) https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt
- [x] (http) https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt
- [x] (http) https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt
- [x] (http) https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/http.txt
- [x] (http) https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxy-list/data.txt
- [x] (http) https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/http.txt
- [x] (http) https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/https.txt
- [x] (http) https://raw.githubusercontent.com/zevtyardt/proxy-list/main/http.txt
- [x] (http) https://rootjazz.com/proxies/proxies.txt
- [x] (http) https://sheesh.rip/http.txt
- [x] (http) https://spys.me/proxy.txt
- [x] (http) https://www.freeproxychecker.com/result/http_proxies.txt
- [x] (http) https://www.juproxy.com/free_api
- [x] (http) https://www.proxy-list.download/api/v1/get?type=http
- [x] (http) https://www.proxy-list.download/api/v1/get?type=https
- [x] (socks4) https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4
- [x] (socks4) https://openproxylist.xyz/socks4.txt
- [x] (socks4) https://proxyscan.io/download?type=socks4
- [x] (socks4) https://proxysearcher.sourceforge.net/Proxy%20List.php?type=socks
- [x] (socks4) https://proxyspace.pro/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/B4RC0DE-TM/proxy-list/main/SOCKS4.txt
- [x] (socks4) https://raw.githubusercontent.com/BlackSnowDot/proxylist-update-every-minute/main/socks.txt
- [x] (socks4) https://raw.githubusercontent.com/fahimscirex/proxybd/master/proxylist/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/hanwayTech/free-proxy-list/main/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/HyperBeats/proxy-list/main/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/miyukii-chan/proxy-list/master/proxies/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/ObcbO/getproxy/master/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/socks4/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/proxylist-to/proxy-list/main/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/ReCaree/proxy-scrapper/master/proxy/socks4-removed.txt
- [x] (socks4) https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt
- [x] (socks4) https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/socks4.txt
- [x] (socks4) https://raw.githubusercontent.com/zevtyardt/proxy-list/main/socks4.txt
- [x] (socks4) https://spys.me/socks.txt
- [x] (socks4) https://www.freeproxychecker.com/result/socks4_proxies.txt
- [x] (socks4) https://www.proxy-list.download/api/v1/get?type=socks4
- [x] (socks5) https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5
- [x] (socks5) https://openproxylist.xyz/socks5.txt
- [x] (socks5) https://proxyscan.io/download?type=socks5
- [x] (socks5) https://proxysearcher.sourceforge.net/Proxy%20List.php?type=socks
- [x] (socks5) https://proxyspace.pro/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/B4RC0DE-TM/proxy-list/main/SOCKS5.txt
- [x] (socks5) https://raw.githubusercontent.com/fahimscirex/proxybd/master/proxylist/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/hanwayTech/free-proxy-list/main/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt
- [x] (socks5) https://raw.githubusercontent.com/HyperBeats/proxy-list/main/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/manuGMG/proxy-365/main/SOCKS5.txt
- [x] (socks5) https://raw.githubusercontent.com/miyukii-chan/proxy-list/master/proxies/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/ObcbO/getproxy/master/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/socks5/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/proxylist-to/proxy-list/main/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/ReCaree/proxy-scrapper/master/proxy/socks5-removed.txt
- [x] (socks5) https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt
- [x] (socks5) https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/socks5.txt
- [x] (socks5) https://raw.githubusercontent.com/zevtyardt/proxy-list/main/socks5.txt
- [x] (socks5) https://spys.me/socks.txt
- [x] (socks5) https://www.freeproxychecker.com/result/socks5_proxies.txt
- [x] (socks5) https://www.proxy-list.download/api/v1/get?type=socks5
- [x] https://hidemy.name/en/proxy-list/
- [x] https://proxylist.geonode.com/ & https://geonode.com/free-proxy-list/
- [x] https://vpnoverview.com/privacy/anonymous-browsing/free-proxy-servers/
- [x] https://www.coderduck.com/free-proxy-list (stale)
- [x] https://www.proxy-list.download/ (stale?)
- [x] https://www.proxyscan.io/api (lol)

Obsolete:

- [x] ~https://anonymouse.cz/proxy-list/~

**Comment by doomedraven** [comment]
Looks like second one is dead now

**Comment by nfx** [comment]
@doomedraven thank you! Please help triaging.

**Comment by doomedraven** [comment]
i will for sure

**Comment by doomedraven** [comment]
https://github.com/nfx/slrp/pull/46
Please mark those as implemented

```
 (socks4) https://openproxylist.xyz/socks4.txt
 (http) https://openproxylist.xyz/http.txt
 (socks5) https://openproxylist.xyz/socks5.txt
 (http) https://www.freeproxychecker.com/result/http_proxies.txt
 (socks4) https://www.freeproxychecker.com/result/socks4_proxies.txt
 (socks5) https://www.freeproxychecker.com/result/socks5_proxies.txt
 (socks5) https://www.proxy-list.download/api/v1/get?type=socks5
 (socks4) https://www.proxy-list.download/api/v1/get?type=socks4
 (http) https://www.proxy-list.download/api/v1/get?type=http
 (https) https://www.proxy-list.download/api/v1/get?type=https
 (http) https://api.proxyscrape.com/v2/?request=getproxies&protocol=http
 (socks4) https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4
 (socks5) https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5
 (socks5) https://proxyspace.pro/socks5.txt
 (socks4) https://proxyspace.pro/socks4.txt
 (http) https://proxyspace.pro/http.txt
 (http) https://proxyspace.pro/https.txt
 (http) https://sheesh.rip/http.txt
 (socks4) https://sheesh.rip/socks4
 (socks5) https://sheesh.rip/socks5
 (http) https://rootjazz.com/proxies/proxies.txt
 https://proxyscan.io/download?type=http
 https://proxyscan.io/download?type=https
 https://proxyscan.io/download?type=socks4
 https://proxyscan.io/download?type=socks5
(http) https://www.juproxy.com/free_api
 
 # there is another types but only supports 2 requests per 5 mins
 (http) https://api.good-proxies.ru/getfree.php?count=1000&ping=8000&time=600&works=500&key=freeproxy
```

**Comment by doomedraven** [comment]
https://github.com/nfx/slrp/pull/49 -> (http) https://www.megaproxylist.net/
