### ISSUE TITLE
Proxies page filter error on empty result

### ISSUE THREAD

**Issue by Ar-Kan** [nfx/slrp#97]
When the filter on Proxies page has zero results, it throws `json: unsupported value: NaN` exception, instead of returning 0.

![image](https://github.com/nfx/slrp/assets/35047123/ca6001c0-2e06-405f-8591-52765b96c15d)

**Comment by nfx** [comment]
uh oh, that's interesting - error should have been different

**Comment by nfx** [comment]
will be fixed with the switch to the new query engine
